/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.contacts.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contacts implements java.io.Serializable {

	private static final long serialVersionUID = -1186552464;

	private java.lang.Integer       contactId;
	private java.lang.Integer       categoryId;
	private java.lang.String        revisionStatus;
	private org.joda.time.DateTime  revisionTimestamp;
	private java.lang.String        publicUid;
	private java.lang.Boolean       isList;
	private java.lang.String        searchfield;
	private java.lang.String        title;
	private java.lang.String        firstname;
	private java.lang.String        lastname;
	private java.lang.String        nickname;
	private java.lang.String        gender;
	private java.lang.String        company;
	private java.lang.String        function;
	private java.lang.String        workAddress;
	private java.lang.String        workCity;
	private java.lang.String        workState;
	private java.lang.String        workPostalcode;
	private java.lang.String        workCountry;
	private java.lang.String        workTelephone;
	private java.lang.String        workTelephone2;
	private java.lang.String        workFax;
	private java.lang.String        workMobile;
	private java.lang.String        workPager;
	private java.lang.String        workEmail;
	private java.lang.String        workIm;
	private java.lang.String        assistant;
	private java.lang.String        assistantTelephone;
	private java.lang.String        department;
	private java.lang.String        manager;
	private java.lang.String        homeAddress;
	private java.lang.String        homeCity;
	private java.lang.String        homeState;
	private java.lang.String        homePostalcode;
	private java.lang.String        homeCountry;
	private java.lang.String        homeTelephone;
	private java.lang.String        homeTelephone2;
	private java.lang.String        homeFax;
	private java.lang.String        homeMobile;
	private java.lang.String        homePager;
	private java.lang.String        homeEmail;
	private java.lang.String        homeIm;
	private java.lang.String        partner;
	private org.joda.time.LocalDate birthday;
	private org.joda.time.LocalDate anniversary;
	private java.lang.String        otherAddress;
	private java.lang.String        otherCity;
	private java.lang.String        otherState;
	private java.lang.String        otherPostalcode;
	private java.lang.String        otherCountry;
	private java.lang.String        otherEmail;
	private java.lang.String        otherIm;
	private java.lang.String        url;
	private java.lang.String        notes;
	private java.lang.Integer       revisionSequence;
	private java.lang.String        href;
	private java.lang.String        etag;

	public Contacts() {}

	public Contacts(
		java.lang.Integer       contactId,
		java.lang.Integer       categoryId,
		java.lang.String        revisionStatus,
		org.joda.time.DateTime  revisionTimestamp,
		java.lang.String        publicUid,
		java.lang.Boolean       isList,
		java.lang.String        searchfield,
		java.lang.String        title,
		java.lang.String        firstname,
		java.lang.String        lastname,
		java.lang.String        nickname,
		java.lang.String        gender,
		java.lang.String        company,
		java.lang.String        function,
		java.lang.String        workAddress,
		java.lang.String        workCity,
		java.lang.String        workState,
		java.lang.String        workPostalcode,
		java.lang.String        workCountry,
		java.lang.String        workTelephone,
		java.lang.String        workTelephone2,
		java.lang.String        workFax,
		java.lang.String        workMobile,
		java.lang.String        workPager,
		java.lang.String        workEmail,
		java.lang.String        workIm,
		java.lang.String        assistant,
		java.lang.String        assistantTelephone,
		java.lang.String        department,
		java.lang.String        manager,
		java.lang.String        homeAddress,
		java.lang.String        homeCity,
		java.lang.String        homeState,
		java.lang.String        homePostalcode,
		java.lang.String        homeCountry,
		java.lang.String        homeTelephone,
		java.lang.String        homeTelephone2,
		java.lang.String        homeFax,
		java.lang.String        homeMobile,
		java.lang.String        homePager,
		java.lang.String        homeEmail,
		java.lang.String        homeIm,
		java.lang.String        partner,
		org.joda.time.LocalDate birthday,
		org.joda.time.LocalDate anniversary,
		java.lang.String        otherAddress,
		java.lang.String        otherCity,
		java.lang.String        otherState,
		java.lang.String        otherPostalcode,
		java.lang.String        otherCountry,
		java.lang.String        otherEmail,
		java.lang.String        otherIm,
		java.lang.String        url,
		java.lang.String        notes,
		java.lang.Integer       revisionSequence,
		java.lang.String        href,
		java.lang.String        etag
	) {
		this.contactId = contactId;
		this.categoryId = categoryId;
		this.revisionStatus = revisionStatus;
		this.revisionTimestamp = revisionTimestamp;
		this.publicUid = publicUid;
		this.isList = isList;
		this.searchfield = searchfield;
		this.title = title;
		this.firstname = firstname;
		this.lastname = lastname;
		this.nickname = nickname;
		this.gender = gender;
		this.company = company;
		this.function = function;
		this.workAddress = workAddress;
		this.workCity = workCity;
		this.workState = workState;
		this.workPostalcode = workPostalcode;
		this.workCountry = workCountry;
		this.workTelephone = workTelephone;
		this.workTelephone2 = workTelephone2;
		this.workFax = workFax;
		this.workMobile = workMobile;
		this.workPager = workPager;
		this.workEmail = workEmail;
		this.workIm = workIm;
		this.assistant = assistant;
		this.assistantTelephone = assistantTelephone;
		this.department = department;
		this.manager = manager;
		this.homeAddress = homeAddress;
		this.homeCity = homeCity;
		this.homeState = homeState;
		this.homePostalcode = homePostalcode;
		this.homeCountry = homeCountry;
		this.homeTelephone = homeTelephone;
		this.homeTelephone2 = homeTelephone2;
		this.homeFax = homeFax;
		this.homeMobile = homeMobile;
		this.homePager = homePager;
		this.homeEmail = homeEmail;
		this.homeIm = homeIm;
		this.partner = partner;
		this.birthday = birthday;
		this.anniversary = anniversary;
		this.otherAddress = otherAddress;
		this.otherCity = otherCity;
		this.otherState = otherState;
		this.otherPostalcode = otherPostalcode;
		this.otherCountry = otherCountry;
		this.otherEmail = otherEmail;
		this.otherIm = otherIm;
		this.url = url;
		this.notes = notes;
		this.revisionSequence = revisionSequence;
		this.href = href;
		this.etag = etag;
	}

	public java.lang.Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(java.lang.Integer contactId) {
		this.contactId = contactId;
	}

	public java.lang.Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		this.categoryId = categoryId;
	}

	public java.lang.String getRevisionStatus() {
		return this.revisionStatus;
	}

	public void setRevisionStatus(java.lang.String revisionStatus) {
		this.revisionStatus = revisionStatus;
	}

	public org.joda.time.DateTime getRevisionTimestamp() {
		return this.revisionTimestamp;
	}

	public void setRevisionTimestamp(org.joda.time.DateTime revisionTimestamp) {
		this.revisionTimestamp = revisionTimestamp;
	}

	public java.lang.String getPublicUid() {
		return this.publicUid;
	}

	public void setPublicUid(java.lang.String publicUid) {
		this.publicUid = publicUid;
	}

	public java.lang.Boolean getIsList() {
		return this.isList;
	}

	public void setIsList(java.lang.Boolean isList) {
		this.isList = isList;
	}

	public java.lang.String getSearchfield() {
		return this.searchfield;
	}

	public void setSearchfield(java.lang.String searchfield) {
		this.searchfield = searchfield;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(java.lang.String firstname) {
		this.firstname = firstname;
	}

	public java.lang.String getLastname() {
		return this.lastname;
	}

	public void setLastname(java.lang.String lastname) {
		this.lastname = lastname;
	}

	public java.lang.String getNickname() {
		return this.nickname;
	}

	public void setNickname(java.lang.String nickname) {
		this.nickname = nickname;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getCompany() {
		return this.company;
	}

	public void setCompany(java.lang.String company) {
		this.company = company;
	}

	public java.lang.String getFunction() {
		return this.function;
	}

	public void setFunction(java.lang.String function) {
		this.function = function;
	}

	public java.lang.String getWorkAddress() {
		return this.workAddress;
	}

	public void setWorkAddress(java.lang.String workAddress) {
		this.workAddress = workAddress;
	}

	public java.lang.String getWorkCity() {
		return this.workCity;
	}

	public void setWorkCity(java.lang.String workCity) {
		this.workCity = workCity;
	}

	public java.lang.String getWorkState() {
		return this.workState;
	}

	public void setWorkState(java.lang.String workState) {
		this.workState = workState;
	}

	public java.lang.String getWorkPostalcode() {
		return this.workPostalcode;
	}

	public void setWorkPostalcode(java.lang.String workPostalcode) {
		this.workPostalcode = workPostalcode;
	}

	public java.lang.String getWorkCountry() {
		return this.workCountry;
	}

	public void setWorkCountry(java.lang.String workCountry) {
		this.workCountry = workCountry;
	}

	public java.lang.String getWorkTelephone() {
		return this.workTelephone;
	}

	public void setWorkTelephone(java.lang.String workTelephone) {
		this.workTelephone = workTelephone;
	}

	public java.lang.String getWorkTelephone2() {
		return this.workTelephone2;
	}

	public void setWorkTelephone2(java.lang.String workTelephone2) {
		this.workTelephone2 = workTelephone2;
	}

	public java.lang.String getWorkFax() {
		return this.workFax;
	}

	public void setWorkFax(java.lang.String workFax) {
		this.workFax = workFax;
	}

	public java.lang.String getWorkMobile() {
		return this.workMobile;
	}

	public void setWorkMobile(java.lang.String workMobile) {
		this.workMobile = workMobile;
	}

	public java.lang.String getWorkPager() {
		return this.workPager;
	}

	public void setWorkPager(java.lang.String workPager) {
		this.workPager = workPager;
	}

	public java.lang.String getWorkEmail() {
		return this.workEmail;
	}

	public void setWorkEmail(java.lang.String workEmail) {
		this.workEmail = workEmail;
	}

	public java.lang.String getWorkIm() {
		return this.workIm;
	}

	public void setWorkIm(java.lang.String workIm) {
		this.workIm = workIm;
	}

	public java.lang.String getAssistant() {
		return this.assistant;
	}

	public void setAssistant(java.lang.String assistant) {
		this.assistant = assistant;
	}

	public java.lang.String getAssistantTelephone() {
		return this.assistantTelephone;
	}

	public void setAssistantTelephone(java.lang.String assistantTelephone) {
		this.assistantTelephone = assistantTelephone;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public java.lang.String getManager() {
		return this.manager;
	}

	public void setManager(java.lang.String manager) {
		this.manager = manager;
	}

	public java.lang.String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(java.lang.String homeAddress) {
		this.homeAddress = homeAddress;
	}

	public java.lang.String getHomeCity() {
		return this.homeCity;
	}

	public void setHomeCity(java.lang.String homeCity) {
		this.homeCity = homeCity;
	}

	public java.lang.String getHomeState() {
		return this.homeState;
	}

	public void setHomeState(java.lang.String homeState) {
		this.homeState = homeState;
	}

	public java.lang.String getHomePostalcode() {
		return this.homePostalcode;
	}

	public void setHomePostalcode(java.lang.String homePostalcode) {
		this.homePostalcode = homePostalcode;
	}

	public java.lang.String getHomeCountry() {
		return this.homeCountry;
	}

	public void setHomeCountry(java.lang.String homeCountry) {
		this.homeCountry = homeCountry;
	}

	public java.lang.String getHomeTelephone() {
		return this.homeTelephone;
	}

	public void setHomeTelephone(java.lang.String homeTelephone) {
		this.homeTelephone = homeTelephone;
	}

	public java.lang.String getHomeTelephone2() {
		return this.homeTelephone2;
	}

	public void setHomeTelephone2(java.lang.String homeTelephone2) {
		this.homeTelephone2 = homeTelephone2;
	}

	public java.lang.String getHomeFax() {
		return this.homeFax;
	}

	public void setHomeFax(java.lang.String homeFax) {
		this.homeFax = homeFax;
	}

	public java.lang.String getHomeMobile() {
		return this.homeMobile;
	}

	public void setHomeMobile(java.lang.String homeMobile) {
		this.homeMobile = homeMobile;
	}

	public java.lang.String getHomePager() {
		return this.homePager;
	}

	public void setHomePager(java.lang.String homePager) {
		this.homePager = homePager;
	}

	public java.lang.String getHomeEmail() {
		return this.homeEmail;
	}

	public void setHomeEmail(java.lang.String homeEmail) {
		this.homeEmail = homeEmail;
	}

	public java.lang.String getHomeIm() {
		return this.homeIm;
	}

	public void setHomeIm(java.lang.String homeIm) {
		this.homeIm = homeIm;
	}

	public java.lang.String getPartner() {
		return this.partner;
	}

	public void setPartner(java.lang.String partner) {
		this.partner = partner;
	}

	public org.joda.time.LocalDate getBirthday() {
		return this.birthday;
	}

	public void setBirthday(org.joda.time.LocalDate birthday) {
		this.birthday = birthday;
	}

	public org.joda.time.LocalDate getAnniversary() {
		return this.anniversary;
	}

	public void setAnniversary(org.joda.time.LocalDate anniversary) {
		this.anniversary = anniversary;
	}

	public java.lang.String getOtherAddress() {
		return this.otherAddress;
	}

	public void setOtherAddress(java.lang.String otherAddress) {
		this.otherAddress = otherAddress;
	}

	public java.lang.String getOtherCity() {
		return this.otherCity;
	}

	public void setOtherCity(java.lang.String otherCity) {
		this.otherCity = otherCity;
	}

	public java.lang.String getOtherState() {
		return this.otherState;
	}

	public void setOtherState(java.lang.String otherState) {
		this.otherState = otherState;
	}

	public java.lang.String getOtherPostalcode() {
		return this.otherPostalcode;
	}

	public void setOtherPostalcode(java.lang.String otherPostalcode) {
		this.otherPostalcode = otherPostalcode;
	}

	public java.lang.String getOtherCountry() {
		return this.otherCountry;
	}

	public void setOtherCountry(java.lang.String otherCountry) {
		this.otherCountry = otherCountry;
	}

	public java.lang.String getOtherEmail() {
		return this.otherEmail;
	}

	public void setOtherEmail(java.lang.String otherEmail) {
		this.otherEmail = otherEmail;
	}

	public java.lang.String getOtherIm() {
		return this.otherIm;
	}

	public void setOtherIm(java.lang.String otherIm) {
		this.otherIm = otherIm;
	}

	public java.lang.String getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public java.lang.Integer getRevisionSequence() {
		return this.revisionSequence;
	}

	public void setRevisionSequence(java.lang.Integer revisionSequence) {
		this.revisionSequence = revisionSequence;
	}

	public java.lang.String getHref() {
		return this.href;
	}

	public void setHref(java.lang.String href) {
		this.href = href;
	}

	public java.lang.String getEtag() {
		return this.etag;
	}

	public void setEtag(java.lang.String etag) {
		this.etag = etag;
	}
}
