/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.contacts.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>contacts</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.sonicle.webtop.contacts.jooq.tables.records.CategoriesRecord, java.lang.Integer> IDENTITY_CATEGORIES = Identities0.IDENTITY_CATEGORIES;
	public static final org.jooq.Identity<com.sonicle.webtop.contacts.jooq.tables.records.ListRecipientsRecord, java.lang.Integer> IDENTITY_LIST_RECIPIENTS = Identities0.IDENTITY_LIST_RECIPIENTS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.CategoriesRecord> CATEGORIES_PKEY = UniqueKeys0.CATEGORIES_PKEY;
	public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.ContactsRecord> CONTACTS_PKEY = UniqueKeys0.CONTACTS_PKEY;
	public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.ContactsPicturesRecord> CONTACTS_PICTURES_PKEY = UniqueKeys0.CONTACTS_PICTURES_PKEY;
	public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.ListRecipientsRecord> LIST_RECIPIENTS_PKEY = UniqueKeys0.LIST_RECIPIENTS_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.sonicle.webtop.contacts.jooq.tables.records.CategoriesRecord, java.lang.Integer> IDENTITY_CATEGORIES = createIdentity(com.sonicle.webtop.contacts.jooq.tables.Categories.CATEGORIES, com.sonicle.webtop.contacts.jooq.tables.Categories.CATEGORIES.CATEGORY_ID);
		public static org.jooq.Identity<com.sonicle.webtop.contacts.jooq.tables.records.ListRecipientsRecord, java.lang.Integer> IDENTITY_LIST_RECIPIENTS = createIdentity(com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS, com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS.LIST_RECIPIENT_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.CategoriesRecord> CATEGORIES_PKEY = createUniqueKey(com.sonicle.webtop.contacts.jooq.tables.Categories.CATEGORIES, com.sonicle.webtop.contacts.jooq.tables.Categories.CATEGORIES.CATEGORY_ID);
		public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.ContactsRecord> CONTACTS_PKEY = createUniqueKey(com.sonicle.webtop.contacts.jooq.tables.Contacts.CONTACTS, com.sonicle.webtop.contacts.jooq.tables.Contacts.CONTACTS.CONTACT_ID);
		public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.ContactsPicturesRecord> CONTACTS_PICTURES_PKEY = createUniqueKey(com.sonicle.webtop.contacts.jooq.tables.ContactsPictures.CONTACTS_PICTURES, com.sonicle.webtop.contacts.jooq.tables.ContactsPictures.CONTACTS_PICTURES.CONTACT_ID);
		public static final org.jooq.UniqueKey<com.sonicle.webtop.contacts.jooq.tables.records.ListRecipientsRecord> LIST_RECIPIENTS_PKEY = createUniqueKey(com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS, com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS.LIST_RECIPIENT_ID);
	}
}
