/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.contacts.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListRecipientsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.contacts.jooq.tables.records.ListRecipientsRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1446752264;

	/**
	 * Setter for <code>contacts.list_recipients.list_recipient_id</code>.
	 */
	public void setListRecipientId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>contacts.list_recipients.list_recipient_id</code>.
	 */
	public java.lang.Integer getListRecipientId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>contacts.list_recipients.contact_id</code>.
	 */
	public void setContactId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>contacts.list_recipients.contact_id</code>.
	 */
	public java.lang.Integer getContactId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>contacts.list_recipients.recipient</code>.
	 */
	public void setRecipient(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>contacts.list_recipients.recipient</code>.
	 */
	public java.lang.String getRecipient() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>contacts.list_recipients.recipient_type</code>.
	 */
	public void setRecipientType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>contacts.list_recipients.recipient_type</code>.
	 */
	public java.lang.String getRecipientType() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS.LIST_RECIPIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS.CONTACT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS.RECIPIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS.RECIPIENT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getListRecipientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getContactId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRecipient();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRecipientType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListRecipientsRecord value1(java.lang.Integer value) {
		setListRecipientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListRecipientsRecord value2(java.lang.Integer value) {
		setContactId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListRecipientsRecord value3(java.lang.String value) {
		setRecipient(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListRecipientsRecord value4(java.lang.String value) {
		setRecipientType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListRecipientsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ListRecipientsRecord
	 */
	public ListRecipientsRecord() {
		super(com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS);
	}

	/**
	 * Create a detached, initialised ListRecipientsRecord
	 */
	public ListRecipientsRecord(java.lang.Integer listRecipientId, java.lang.Integer contactId, java.lang.String recipient, java.lang.String recipientType) {
		super(com.sonicle.webtop.contacts.jooq.tables.ListRecipients.LIST_RECIPIENTS);

		setValue(0, listRecipientId);
		setValue(1, contactId);
		setValue(2, recipient);
		setValue(3, recipientType);
	}
}
